// <auto-generated />
using System;
using DraughtSurveyWebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DraughtSurveyWebApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250805185737_RemovedRequiredUserHydrostaticTableHeader")]
    partial class RemovedRequiredUserHydrostaticTableHeader
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.15");

            modelBuilder.Entity("DraughtSurveyWebApp.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdminNote")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<int>("LoginCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DraughtSurveyWebApp.Models.CargoInput", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BerthNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("CargoName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Consignee")
                        .HasColumnType("TEXT");

                    b.Property<double?>("DeclaredWeight")
                        .HasColumnType("REAL");

                    b.Property<string>("DischargingPort")
                        .HasColumnType("TEXT");

                    b.Property<int>("InspectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoadingTerminal")
                        .HasColumnType("TEXT");

                    b.Property<string>("Shipper")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InspectionId")
                        .IsUnique();

                    b.ToTable("CargoInputs");
                });

            modelBuilder.Entity("DraughtSurveyWebApp.Models.CargoResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("CargoByDraughtSurvey")
                        .HasColumnType("REAL");

                    b.Property<double?>("DifferenceWithBL_Mt")
                        .HasColumnType("REAL");

                    b.Property<double?>("DifferenceWithBL_Percents")
                        .HasColumnType("REAL");

                    b.Property<double?>("DifferenceWithSDWT_Percents")
                        .HasColumnType("REAL");

                    b.Property<int>("InspectionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InspectionId")
                        .IsUnique();

                    b.ToTable("CargoResults");
                });

            modelBuilder.Entity("DraughtSurveyWebApp.Models.DeductiblesInput", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Ballast")
                        .HasColumnType("REAL");

                    b.Property<double?>("DieselOil")
                        .HasColumnType("REAL");

                    b.Property<int>("DraughtSurveyBlockId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("FreshWater")
                        .HasColumnType("REAL");

                    b.Property<double?>("FuelOil")
                        .HasColumnType("REAL");

                    b.Property<double?>("LubOil")
                        .HasColumnType("REAL");

                    b.Property<double?>("Others")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("DraughtSurveyBlockId")
                        .IsUnique();

                    b.ToTable("DeductiblesInputs");
                });

            modelBuilder.Entity("DraughtSurveyWebApp.Models.DeductiblesResults", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DraughtSurveyBlockId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("TotalDeductibles")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("DraughtSurveyBlockId")
                        .IsUnique();

                    b.ToTable("DeductiblesResults");
                });

            modelBuilder.Entity("DraughtSurveyWebApp.Models.DraughtSurveyBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CargoOperationsDateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("InspectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SurveyTimeEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SurveyTimeStart")
                        .HasColumnType("TEXT");

                    b.Property<int>("SurveyType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InspectionId");

                    b.ToTable("DraughtSurveyBlocks");
                });

            modelBuilder.Entity("DraughtSurveyWebApp.Models.DraughtsInput", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("DistanceAft")
                        .HasColumnType("REAL");

                    b.Property<double?>("DistanceFwd")
                        .HasColumnType("REAL");

                    b.Property<double?>("DistanceMid")
                        .HasColumnType("REAL");

                    b.Property<double?>("DraughtAftPS")
                        .HasColumnType("REAL");

                    b.Property<double?>("DraughtAftSS")
                        .HasColumnType("REAL");

                    b.Property<double?>("DraughtFwdPS")
                        .HasColumnType("REAL");

                    b.Property<double?>("DraughtFwdSS")
                        .HasColumnType("REAL");

                    b.Property<double?>("DraughtMidPS")
                        .HasColumnType("REAL");

                    b.Property<double?>("DraughtMidSS")
                        .HasColumnType("REAL");

                    b.Property<int>("DraughtSurveyBlockId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("KeelCorrection")
                        .HasColumnType("REAL");

                    b.Property<double?>("SeaWaterDensity")
                        .HasColumnType("REAL");

                    b.Property<double?>("Swell")
                        .HasColumnType("REAL");

                    b.Property<bool?>("isAftDistanceToFwd")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("isFwdDistancetoFwd")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("isMidDistanceToFwd")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DraughtSurveyBlockId")
                        .IsUnique();

                    b.ToTable("DraughtsInputs");
                });

            modelBuilder.Entity("DraughtSurveyWebApp.Models.DraughtsResults", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("DifferenceMTC1MTC2")
                        .HasColumnType("REAL");

                    b.Property<double?>("DraughtCorrectedAft")
                        .HasColumnType("REAL");

                    b.Property<double?>("DraughtCorrectedFwd")
                        .HasColumnType("REAL");

                    b.Property<double?>("DraughtCorrectedMid")
                        .HasColumnType("REAL");

                    b.Property<double?>("DraughtCorrectionAft")
                        .HasColumnType("REAL");

                    b.Property<double?>("DraughtCorrectionFwd")
                        .HasColumnType("REAL");

                    b.Property<double?>("DraughtCorrectionMid")
                        .HasColumnType("REAL");

                    b.Property<double?>("DraughtMeanAft")
                        .HasColumnType("REAL");

                    b.Property<double?>("DraughtMeanFwd")
                        .HasColumnType("REAL");

                    b.Property<double?>("DraughtMeanMid")
                        .HasColumnType("REAL");

                    b.Property<int>("DraughtSurveyBlockId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Heel")
                        .HasColumnType("REAL");

                    b.Property<double?>("HoggingSagging")
                        .HasColumnType("REAL");

                    b.Property<double?>("MeanAdjustedDraught")
                        .HasColumnType("REAL");

                    b.Property<double?>("MeanAdjustedDraughtAfterKeelCorrection")
                        .HasColumnType("REAL");

                    b.Property<double?>("MeanFwdAftDraught")
                        .HasColumnType("REAL");

                    b.Property<double?>("MeanOfMeanDraught")
                        .HasColumnType("REAL");

                    b.Property<double?>("TrimApparent")
                        .HasColumnType("REAL");

                    b.Property<double?>("TrimCorrected")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("DraughtSurveyBlockId")
                        .IsUnique();

                    b.ToTable("DraughtsResults");
                });

            modelBuilder.Entity("DraughtSurveyWebApp.Models.HydrostaticInput", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("DisplacementAbove")
                        .HasColumnType("REAL");

                    b.Property<double?>("DisplacementBelow")
                        .HasColumnType("REAL");

                    b.Property<double?>("DraughtAbove")
                        .HasColumnType("REAL");

                    b.Property<double?>("DraughtBelow")
                        .HasColumnType("REAL");

                    b.Property<int>("DraughtSurveyBlockId")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsLCFForward")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("LCFAbove")
                        .HasColumnType("REAL");

                    b.Property<double?>("LCFBelow")
                        .HasColumnType("REAL");

                    b.Property<double?>("LCFfromAftAbove")
                        .HasColumnType("REAL");

                    b.Property<double?>("LCFfromAftBelow")
                        .HasColumnType("REAL");

                    b.Property<double?>("MTCMinus50Above")
                        .HasColumnType("REAL");

                    b.Property<double?>("MTCMinus50Below")
                        .HasColumnType("REAL");

                    b.Property<double?>("MTCPlus50Above")
                        .HasColumnType("REAL");

                    b.Property<double?>("MTCPlus50Below")
                        .HasColumnType("REAL");

                    b.Property<double?>("TPCAbove")
                        .HasColumnType("REAL");

                    b.Property<double?>("TPCBelow")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("DraughtSurveyBlockId")
                        .IsUnique();

                    b.ToTable("HydrostaticInputs");
                });

            modelBuilder.Entity("DraughtSurveyWebApp.Models.HydrostaticResults", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("CargoPlusConstant")
                        .HasColumnType("REAL");

                    b.Property<double?>("DisplacementCorrectedForDensity")
                        .HasColumnType("REAL");

                    b.Property<double?>("DisplacementCorrectedForTrim")
                        .HasColumnType("REAL");

                    b.Property<double?>("DisplacementFromTable")
                        .HasColumnType("REAL");

                    b.Property<int>("DraughtSurveyBlockId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("FirstTrimCorrection")
                        .HasColumnType("REAL");

                    b.Property<double?>("LCFFromTable")
                        .HasColumnType("REAL");

                    b.Property<double?>("MTCMinus50FromTable")
                        .HasColumnType("REAL");

                    b.Property<double?>("MTCPlus50FromTable")
                        .HasColumnType("REAL");

                    b.Property<double?>("NettoDisplacement")
                        .HasColumnType("REAL");

                    b.Property<double?>("SecondTrimCorrection")
                        .HasColumnType("REAL");

                    b.Property<double?>("TPCFromTable")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("DraughtSurveyBlockId")
                        .IsUnique();

                    b.ToTable("HydrostaticResults");
                });

            modelBuilder.Entity("DraughtSurveyWebApp.Models.Inspection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyReference")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OperationType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Port")
                        .HasColumnType("TEXT");

                    b.Property<string>("VesselName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("notApplyAutoFillingHydrostatics")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("notShowInputWarnings")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Inspections");
                });

            modelBuilder.Entity("DraughtSurveyWebApp.Models.UserHydrostaticTableHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IMO")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("TableStep")
                        .HasColumnType("REAL");

                    b.Property<string>("VesselName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("UserHydrostaticTableHeaders");
                });

            modelBuilder.Entity("DraughtSurveyWebApp.Models.UserHydrostaticTableRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Displacement")
                        .HasColumnType("REAL");

                    b.Property<double>("Draught")
                        .HasColumnType("REAL");

                    b.Property<bool?>("IsLcfForward")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("LCF")
                        .HasColumnType("REAL");

                    b.Property<double?>("MTCMinus50")
                        .HasColumnType("REAL");

                    b.Property<double?>("MTCPlus50")
                        .HasColumnType("REAL");

                    b.Property<double?>("TPC")
                        .HasColumnType("REAL");

                    b.Property<int>("UserHydrostaticTableHeaderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserHydrostaticTableHeaderId");

                    b.ToTable("UserHydrostaticTableRows");
                });

            modelBuilder.Entity("DraughtSurveyWebApp.Models.VesselInput", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("BM")
                        .HasColumnType("REAL");

                    b.Property<double?>("DeclaredConstant")
                        .HasColumnType("REAL");

                    b.Property<string>("IMO")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InspectionId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("LBP")
                        .HasColumnType("REAL");

                    b.Property<double?>("LS")
                        .HasColumnType("REAL");

                    b.Property<double?>("SDWT")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("InspectionId")
                        .IsUnique();

                    b.ToTable("VesselInputs");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DraughtSurveyWebApp.Models.CargoInput", b =>
                {
                    b.HasOne("DraughtSurveyWebApp.Models.Inspection", "Inspection")
                        .WithOne("CargoInput")
                        .HasForeignKey("DraughtSurveyWebApp.Models.CargoInput", "InspectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inspection");
                });

            modelBuilder.Entity("DraughtSurveyWebApp.Models.CargoResult", b =>
                {
                    b.HasOne("DraughtSurveyWebApp.Models.Inspection", "Inspection")
                        .WithOne("CargoResult")
                        .HasForeignKey("DraughtSurveyWebApp.Models.CargoResult", "InspectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inspection");
                });

            modelBuilder.Entity("DraughtSurveyWebApp.Models.DeductiblesInput", b =>
                {
                    b.HasOne("DraughtSurveyWebApp.Models.DraughtSurveyBlock", "DraughtSurveyBlock")
                        .WithOne("DeductiblesInput")
                        .HasForeignKey("DraughtSurveyWebApp.Models.DeductiblesInput", "DraughtSurveyBlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DraughtSurveyBlock");
                });

            modelBuilder.Entity("DraughtSurveyWebApp.Models.DeductiblesResults", b =>
                {
                    b.HasOne("DraughtSurveyWebApp.Models.DraughtSurveyBlock", "DraughtSurveyBlock")
                        .WithOne("DeductiblesResults")
                        .HasForeignKey("DraughtSurveyWebApp.Models.DeductiblesResults", "DraughtSurveyBlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DraughtSurveyBlock");
                });

            modelBuilder.Entity("DraughtSurveyWebApp.Models.DraughtSurveyBlock", b =>
                {
                    b.HasOne("DraughtSurveyWebApp.Models.Inspection", "Inspection")
                        .WithMany("DraughtSurveyBlocks")
                        .HasForeignKey("InspectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inspection");
                });

            modelBuilder.Entity("DraughtSurveyWebApp.Models.DraughtsInput", b =>
                {
                    b.HasOne("DraughtSurveyWebApp.Models.DraughtSurveyBlock", "DraughtSurveyBlock")
                        .WithOne("DraughtsInput")
                        .HasForeignKey("DraughtSurveyWebApp.Models.DraughtsInput", "DraughtSurveyBlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DraughtSurveyBlock");
                });

            modelBuilder.Entity("DraughtSurveyWebApp.Models.DraughtsResults", b =>
                {
                    b.HasOne("DraughtSurveyWebApp.Models.DraughtSurveyBlock", "DraughtSurveyBlock")
                        .WithOne("DraughtsResults")
                        .HasForeignKey("DraughtSurveyWebApp.Models.DraughtsResults", "DraughtSurveyBlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DraughtSurveyBlock");
                });

            modelBuilder.Entity("DraughtSurveyWebApp.Models.HydrostaticInput", b =>
                {
                    b.HasOne("DraughtSurveyWebApp.Models.DraughtSurveyBlock", "DraughtSurveyBlock")
                        .WithOne("HydrostaticInput")
                        .HasForeignKey("DraughtSurveyWebApp.Models.HydrostaticInput", "DraughtSurveyBlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DraughtSurveyBlock");
                });

            modelBuilder.Entity("DraughtSurveyWebApp.Models.HydrostaticResults", b =>
                {
                    b.HasOne("DraughtSurveyWebApp.Models.DraughtSurveyBlock", "DraughtSurveyBlock")
                        .WithOne("HydrostaticResults")
                        .HasForeignKey("DraughtSurveyWebApp.Models.HydrostaticResults", "DraughtSurveyBlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DraughtSurveyBlock");
                });

            modelBuilder.Entity("DraughtSurveyWebApp.Models.Inspection", b =>
                {
                    b.HasOne("DraughtSurveyWebApp.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("Inspections")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("DraughtSurveyWebApp.Models.UserHydrostaticTableHeader", b =>
                {
                    b.HasOne("DraughtSurveyWebApp.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("DraughtSurveyWebApp.Models.UserHydrostaticTableRow", b =>
                {
                    b.HasOne("DraughtSurveyWebApp.Models.UserHydrostaticTableHeader", "UserHydrostaticTableHeader")
                        .WithMany("UserHydrostaticTableRows")
                        .HasForeignKey("UserHydrostaticTableHeaderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserHydrostaticTableHeader");
                });

            modelBuilder.Entity("DraughtSurveyWebApp.Models.VesselInput", b =>
                {
                    b.HasOne("DraughtSurveyWebApp.Models.Inspection", "Inspection")
                        .WithOne("VesselInput")
                        .HasForeignKey("DraughtSurveyWebApp.Models.VesselInput", "InspectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inspection");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DraughtSurveyWebApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DraughtSurveyWebApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DraughtSurveyWebApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DraughtSurveyWebApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DraughtSurveyWebApp.Models.ApplicationUser", b =>
                {
                    b.Navigation("Inspections");
                });

            modelBuilder.Entity("DraughtSurveyWebApp.Models.DraughtSurveyBlock", b =>
                {
                    b.Navigation("DeductiblesInput");

                    b.Navigation("DeductiblesResults");

                    b.Navigation("DraughtsInput");

                    b.Navigation("DraughtsResults");

                    b.Navigation("HydrostaticInput");

                    b.Navigation("HydrostaticResults");
                });

            modelBuilder.Entity("DraughtSurveyWebApp.Models.Inspection", b =>
                {
                    b.Navigation("CargoInput");

                    b.Navigation("CargoResult");

                    b.Navigation("DraughtSurveyBlocks");

                    b.Navigation("VesselInput");
                });

            modelBuilder.Entity("DraughtSurveyWebApp.Models.UserHydrostaticTableHeader", b =>
                {
                    b.Navigation("UserHydrostaticTableRows");
                });
#pragma warning restore 612, 618
        }
    }
}
